version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: course-platform-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coursedb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: